### ISSUE TITLE
raft messaging via channels?

### ISSUE THREAD

**Issue by droundy** [Albibek/raft-experiment#1]
This isn't really an "issue", but I have been thinking of writing a raft implementation that uses crossbeam channels (see https://github.com/crossbeam-rs/crossbeam-channel) for its API, and does manage the network (with encrypted messages and client adding/removing) doesn't manage the finite state machine, just ensures that every node gets every message in the same order.

I don't know if this would be a design that would appeal to you, but I think it could result in a very clean API that would make it (relatively) easy to write a distributed program without bugs.  The basic idea is that raft is really a broadcast channel with nice guarantees.

So this raft-experiment could evolve to become the raft-channel that I envision, or they could be separate things.

**Comment by Albibek** [comment]
My main goal here is totally separating consensus logic from network and serialization protocols. Working with only enums gives alot of possibilities, including channels.

**Comment by droundy** [comment]
I would be concerned that the result would be something that is very complicated to use, but why no try?

My aim for my (truly hypothetical project) would be a much simpler raft that does more things automatically, but is also more opinionated (e.g. encrypting and authenticating messages).
